### ISSUE TITLE
Can't Install because of Django-Select 2

### ISSUE THREAD

**Issue by JeremyBYU** [aldryn/aldryn-blog#63]
I can't install this app because Django-Select2 is not compatible with Python3 .  I found a specific branch of Django-Select2 with Python 3 support.  I installed it, but aldryn-blog still wants to install the non Python3 version.

``` python
(env2)jeremy@AtlasShrugged ~/Dropbox/Programming/webdevelopment/newtest $ pip install aldryn-blog
Downloading/unpacking aldryn-blog
  Downloading aldryn-blog-0.3.12.tar.gz
  Running setup.py (path:/home/jeremy/Dropbox/Programming/webdevelopment/newtest/env2/build/aldryn-blog/setup.py) egg_info for package aldryn-blog

    warning: no previously-included files matching '*.pyc' found under directory '*'
Downloading/unpacking django-taggit<0.12 (from aldryn-blog)
  Downloading django_taggit-0.11.2-py2.py3-none-any.whl
Downloading/unpacking django-filer (from aldryn-blog)
  Downloading django-filer-0.9.5.tar.gz (739kB): 739kB downloaded
  Running setup.py (path:/home/jeremy/Dropbox/Programming/webdevelopment/newtest/env2/build/django-filer/setup.py) egg_info for package django-filer

Downloading/unpacking django-select2 (from aldryn-blog)
  Downloading Django-Select2-4.2.2.tar.gz (91kB): 91kB downloaded
  Running setup.py (path:/home/jeremy/Dropbox/Programming/webdevelopment/newtest/env2/build/django-select2/setup.py) egg_info for package django-select2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/jeremy/Dropbox/Programming/webdevelopment/newtest/env2/build/django-select2/setup.py", line 154
        print data['error_code']
                 ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/jeremy/Dropbox/Programming/webdevelopment/newtest/env2/build/django-select2/setup.py", line 154

```

Also as a side note I tried this with just a Python2.7 Environment and it worked.  However I used sqlite3 as the database which is supposedly not supported.  It seemed to work just fine.  Whats not supposed to work with sqlite3? 

Thank you!

: (

**Comment by bastiW** [comment]
So, how can I use python3 toghether with aldryn-blog?
